#!/usr/bin/env bash
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# A modified version of the Fabric bootstrap script
# Use positional arguments to select components to install
#
# Has exactly the same functional power of bootstrap.sh

### START OF CODE GENERATED BY Argbash v2.9.0  ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate

# Default values
_positionals=()
_arg_comp=('' )

# if version not passed in, default to latest released version
# if ca version not passed in, default to latest released version
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
# shellcheck source=scripts/dependency-versions.env
. "$SCRIPT_DIR/scripts/dependency-versions.env"
_arg_fabric_version="$FABRIC_VERSION"
_arg_ca_version="$FABRIC_CA_VERSION"

OS=$(uname -s|tr '[:upper:]' '[:lower:]'|sed 's/mingw64_nt.*/windows/')
ARCH=$(uname -m | sed 's/x86_64/amd64/g' | sed 's/aarch64/arm64/g')
PLATFORM=${OS}-${ARCH}

# Fabric < 1.2 uses uname -m for architecture.
MARCH=$(uname -m)

HYPERLEDGER_NAMESPACE=hyperledger
DOCKER_NAMESPACE="${FABRIC_DOCKER_REGISTRY:-${HYPERLEDGER_NAMESPACE}}"


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}

verify_sha256()
{
    local expected=$1
    local file=$2
    if command -v sha256sum >/dev/null; then
        echo "${expected}  ${file}" | sha256sum --check --status
    elif command -v shasum >/dev/null; then
        [ "$(shasum -a 256 "${file}" | awk '{print $1}')" = "${expected}" ]
    else
        die "sha256sum or shasum is required to verify downloaded binaries"
    fi
}

sha256_value()
{
    if command -v sha256sum >/dev/null; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        die "sha256sum or shasum is required to verify installed binaries"
    fi
}


begins_with_short_option()
{
	local first_option all_short_options='fc'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}


print_help()
{
	printf 'Usage: %s [-f|--fabric-version <arg>] [-c|--ca-version <arg>] <comp-1> [<comp-2>] ... [<comp-n>] ...\n' "$0"
	printf '\t%s\n' "<comp> Component to install, one or more of  docker | binary | samples | podman  First letter of component also accepted; If none specified docker | binary | samples is assumed"
	printf '\t%s\n' "-f, --fabric-version: FabricVersion (default: '2.5.16')"
	printf '\t%s\n' "-c, --ca-version: Fabric CA Version (default: '1.5.17')"
}


parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-f|--fabric-version)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_fabric_version="$2"
				shift
				;;
			--fabric-version=*)
				_arg_fabric_version="${_key##--fabric-version=}"
				;;
			-f*)
				_arg_fabric_version="${_key##-f}"
				;;
			-c|--ca-version)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_ca_version="$2"
				shift
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			--ca-version=*)
				_arg_ca_version="${_key##--ca-version=}"
				;;
			-c*)
				_arg_ca_version="${_key##-c}"
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'comp'"
	# test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_comp "
	_our_args=$((${#_positionals[@]} - 1))
	for ((ii = 0; ii < _our_args; ii++))
	do
		_positional_names="$_positional_names _arg_comp[$((ii + 1))]"
	done

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

# End of ARGBASH code

# dockerPull() pulls docker images from fabric and chaincode repositories
# note, if a docker image doesn't exist for a requested release, it will simply
# be skipped, since this script doesn't terminate upon errors.

singleImagePull() {
    #three_digit_image_tag is passed in, e.g. "1.4.7"
    local three_digit_image_tag=$1
    shift
    #two_digit_image_tag is derived, e.g. "1.4", especially useful as a local tag for two digit references
    local two_digit_image_tag
    two_digit_image_tag=$(echo "$three_digit_image_tag" | cut -d'.' -f1,2)


    while [[ $# -gt 0 ]]; do
        local component_name="$1"
        local registry
        registry="$(dockerComponentRegistry "${component_name}" "${three_digit_image_tag}")"
        local image_name="${registry}/fabric-${component_name}:${three_digit_image_tag}"

        echo "====>  ${image_name}"
        ${CONTAINER_CLI} pull "${image_name}"


        ${CONTAINER_CLI} tag "${image_name}" "${DOCKER_NAMESPACE}/fabric-${component_name}"
        ${CONTAINER_CLI} tag "${image_name}" "${DOCKER_NAMESPACE}/fabric-${component_name}:${two_digit_image_tag}"
        # Re-tag 3-digit version to ensure there is a tag without registry prefix
        ${CONTAINER_CLI} tag "${image_name}" "${DOCKER_NAMESPACE}/fabric-${component_name}:${three_digit_image_tag}"

        shift
    done
}

dockerComponentRegistry() {
    if [[ -n ${FABRIC_DOCKER_REGISTRY} ]]; then
        echo -n "${FABRIC_DOCKER_REGISTRY}"
        return
    fi

    local component="$1"
    local image_version="$2"

    # Remove trailing pre-release or metadata identifiers
    image_version="${image_version%%[-+]*}"

    case "${component}" in
        ca)
            echo -n "$(dockerCARegistry "${image_version}")/${HYPERLEDGER_NAMESPACE}"
            ;;
        *)
            echo -n "$(dockerFabricRegistry "${image_version}")/${HYPERLEDGER_NAMESPACE}"
            ;;
    esac
}

dockerCARegistry() {
    local version="$1"

    case "${version}" in
        1.[0-4].*|1.5.[0-9]|1.5.1[0-4])
            echo -n 'docker.io'
            ;;
        *)
            echo -n 'ghcr.io'
            ;;
    esac
}

dockerFabricRegistry() {
    local version="$1"

    case "${version}" in
        1.*|2.[0-4].*|2.5.[0-9]|2.5.10|3.0.0)
            echo -n 'docker.io'
            ;;
        *)
            echo -n 'ghcr.io'
            ;;
    esac
}

cloneSamplesRepo() {
    # clone (if needed) hyperledger/fabric-samples and checkout corresponding
    # version to the binaries and docker images to be downloaded
    if [ -d test-network ]; then
        # if we are in the fabric-samples repo, checkout corresponding version
        echo "==> Already in fabric-samples repo"
    elif [ -d fabric-samples ]; then
        # if fabric-samples repo already cloned and in current directory,
        # cd fabric-samples
        echo "===> Changing directory to fabric-samples"
        cd fabric-samples
    else
        echo "===> Cloning hyperledger/fabric-samples repo"
        git clone --filter=blob:none --no-checkout https://github.com/hyperledger/fabric-samples.git && cd fabric-samples
    fi

    echo "===> Checking out pinned fabric-samples revision ${FABRIC_SAMPLES_COMMIT}"
    git checkout -q --detach "${FABRIC_SAMPLES_COMMIT}"
    [ "$(git rev-parse HEAD)" = "${FABRIC_SAMPLES_COMMIT}" ] || die "fabric-samples revision verification failed"
}

# This will download the .tar.gz
download() {
    local BINARY_FILE=$1
    local URL=$2
    local DEST_DIR=$(pwd)
    local EXPECTED_SHA256
    local TEMP_FILE
    local rc=""
    case "${BINARY_FILE}" in
        hyperledger-fabric-darwin-amd64-2.5.16.tar.gz) EXPECTED_SHA256=18acff3d9b782ddfc11b285af85f6e9f4a8d47504d8e6d230d1993f8e08833a6 ;;
        hyperledger-fabric-darwin-arm64-2.5.16.tar.gz) EXPECTED_SHA256=9f226e9c7e40f81b4f76db349438f8742beeb43d88519b73f2095e4f65f3ab42 ;;
        hyperledger-fabric-linux-amd64-2.5.16.tar.gz) EXPECTED_SHA256=18c91e7f2f11b601e6622cc70454d568af897707ee9adf111e9fa91a233881bf ;;
        hyperledger-fabric-linux-arm64-2.5.16.tar.gz) EXPECTED_SHA256=c3c1809afab1998e9f2dd37ccd7fc5fa97658cdeaaa9ca0de29e896bf6dee029 ;;
        hyperledger-fabric-windows-amd64-2.5.16.tar.gz) EXPECTED_SHA256=fdcefd5e0f9343adf7b2e34461a0d5c531a375ce8c86cf9f4caff48982d07d1c ;;
        hyperledger-fabric-ca-darwin-amd64-1.5.17.tar.gz) EXPECTED_SHA256=1b5ef1fd364aa9cf2e8cceec56adae094a3d3b53bca454635a51cf87911878fc ;;
        hyperledger-fabric-ca-darwin-arm64-1.5.17.tar.gz) EXPECTED_SHA256=de5a283b7d33ae7676795e969cb5e7f26d93e15e1b90788dc0d3d9ba37a098de ;;
        hyperledger-fabric-ca-linux-amd64-1.5.17.tar.gz) EXPECTED_SHA256=839287630fa6f89c8490a424a38b821c1cfe696f2322522ddca5825e61b458e6 ;;
        hyperledger-fabric-ca-linux-arm64-1.5.17.tar.gz) EXPECTED_SHA256=042c477bcfafffdf7060a543bfaced30879c6d0424bfb08e94b12e59a3bc2ae6 ;;
        hyperledger-fabric-ca-windows-amd64-1.5.17.tar.gz) EXPECTED_SHA256=5904e46edc897bbb4c2d553801df7a1313ac5fcdae9af30b15696af3e8e3d4e9 ;;
        *) die "No trusted SHA-256 digest for ${BINARY_FILE}" ;;
    esac
    TEMP_FILE=$(mktemp)
    echo "===> Downloading: " "${URL}"
    if [ -d fabric-samples ]; then
       DEST_DIR="fabric-samples"
    fi
    echo "===> Will unpack to: ${DEST_DIR}"
    curl --fail --location --retry 5 --retry-delay 3 --output "${TEMP_FILE}" "${URL}" || rc=$?
    if [ -z "$rc" ] && ! verify_sha256 "${EXPECTED_SHA256}" "${TEMP_FILE}"; then
        echo "==> SHA-256 verification failed for ${BINARY_FILE}." >&2
        rc=1
    fi
    if [ -z "$rc" ]; then
        tar xzf "${TEMP_FILE}" -C "${DEST_DIR}" || rc=$?
    fi
    rm -f "${TEMP_FILE}"
    if [ -n "$rc" ]; then
        echo "==> There was an error downloading the binary file."
        return 22
    else
        echo "==> Done."
    fi
}

pullBinaries() {
    echo "===> Downloading version ${FABRIC_TAG} platform specific fabric binaries"
    download "${BINARY_FILE}" "https://github.com/hyperledger/fabric/releases/download/v${VERSION}/${BINARY_FILE}"
    if [ $? -eq 22 ]; then
        echo
        echo "------> ${FABRIC_TAG} platform specific fabric binary is not available to download <----"
        echo
        exit
    fi

    echo "===> Downloading version ${CA_TAG} platform specific fabric-ca-client binary"
    download "${CA_BINARY_FILE}" "https://github.com/hyperledger/fabric-ca/releases/download/v${CA_VERSION}/${CA_BINARY_FILE}"
    if [ $? -eq 22 ]; then
        echo
        echo "------> ${CA_TAG} fabric-ca-client binary is not available to download  (Available from 1.1.0-rc1) <----"
        echo
        exit
    fi

    local BIN_ROOT="$(pwd)/bin"
    if [ -d "$(pwd)/fabric-samples/bin" ]; then
        BIN_ROOT="$(pwd)/fabric-samples/bin"
    fi
    [ -x "${BIN_ROOT}/peer" ] || die "Downloaded archive did not install the peer binary"
    {
        echo "FABRIC_VERSION=${VERSION}"
        echo "FABRIC_CA_VERSION=${CA_VERSION}"
        echo "PEER_SHA256=$(sha256_value "${BIN_ROOT}/peer")"
    } > "${BIN_ROOT}/.verified-install"
}

pullImages() {
    command -v  ${CONTAINER_CLI}  >& /dev/null
    NODOCKER=$?
    if [ "${NODOCKER}" == 0 ]; then
        FABRIC_IMAGES=(peer orderer ccenv)
        case "$VERSION" in
        [2-3].*)
            FABRIC_IMAGES+=(baseos)
            shift
            ;;
        esac

        echo "FABRIC_IMAGES:" "${FABRIC_IMAGES[@]}"
        echo "===> Pulling fabric Images"
        singleImagePull "${FABRIC_TAG}" "${FABRIC_IMAGES[@]}"
        echo "===> Pulling fabric ca Image"
        CA_IMAGE=(ca)
        singleImagePull "${CA_TAG}" "${CA_IMAGE[@]}"
        echo "===> List out hyperledger images"
        ${CONTAINER_CLI} images | grep hyperledger
    else
        echo "========================================================="
        echo "${CONTAINER_CLI} not installed, bypassing download of Fabric images"
        echo "========================================================="
    fi
}


# Main code starts here
parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"


VERSION=$_arg_fabric_version
CA_VERSION=$_arg_ca_version

# prior to 1.2.0 architecture was determined by uname -m
if [[ $VERSION =~ ^1\.[0-1]\.* ]]; then
    export FABRIC_TAG=${MARCH}-${VERSION}
    export CA_TAG=${MARCH}-${CA_VERSION}
else
    # starting with 1.2.0, multi-arch images will be default
    : "${CA_TAG:="$CA_VERSION"}"
    : "${FABRIC_TAG:="$VERSION"}"
fi

# Prior to fabric 2.5, use amd64 binaries on darwin-arm64
if [[ $VERSION =~ ^2\.[0-4]\.* ]]; then
  PLATFORM=$(echo $PLATFORM | sed 's/darwin-arm64/darwin-amd64/g')
fi

BINARY_FILE=hyperledger-fabric-${PLATFORM}-${VERSION}.tar.gz
CA_BINARY_FILE=hyperledger-fabric-ca-${PLATFORM}-${CA_VERSION}.tar.gz

# if nothing has been specified, assume everything
if [[ ${_arg_comp[@]} =~ ^$ ]]; then
    echo "No options selected: Getting all samples, binaries, and docker images"
    echo "Abort now if not the intention"
    sleep 3 # just to give a chance to abort if this wasn't intended
    _arg_comp=('samples','binary','docker')
fi

# Process samples first then the binaries. So if the fabric-samples dir is present
# the binaries will go there
if [[ "${_arg_comp[@]}" =~ (^| |,)s(amples)? ]]; then
        echo
        echo "Clone hyperledger/fabric-samples repo"
        echo
        cloneSamplesRepo
fi

if [[ "${_arg_comp[@]}" =~ (^| |,)b(inary)? ]]; then
        echo
        echo "Pull Hyperledger Fabric binaries"
        echo
        pullBinaries
fi

if [[ "${_arg_comp[@]}" =~ (^| |,)p(odman)? ]]; then
        echo
        echo "Pull Hyperledger Fabric podman images"
        echo
        CONTAINER_CLI=podman
        pullImages
fi

if [[ "${_arg_comp[@]}" =~ (^| |,)d(ocker)? ]]; then
        echo
        echo "Pull Hyperledger Fabric docker images"
        echo
        CONTAINER_CLI=docker
        pullImages
fi
