/*
 * IoT Device Identity Registry Contract — Production
 * SPDX-License-Identifier: Apache-2.0
 *
 * Manages device metadata on the Fabric ledger:
 *   - ID          : unique device identifier (alphanumeric + _- , 3-64 chars)
 *   - PublicKey   : device public key (P-256 SPKI PEM)
 *   - Status      : ACTIVE | REVOKED
 *   - RegisteredAt/UpdatedAt : ISO timestamps
 *   - RegisteredBy: client identity (MSP + cert)
 *
 * All state mutations emit chaincode events for off-chain indexing.
 * No hardcoded demo identities — production devices must be registered
 * via RegisterDevice with a P-256 SPKI PEM public key (generated by the
 * simulator's cryptography or device provisioning).
 */

'use strict';

const { Contract } = require('fabric-contract-api');
const crypto = require('node:crypto');
const stringify = require('json-stringify-deterministic');
const sortKeysRecursive = require('sort-keys-recursive');

const ACTIVE_STATUS = 'ACTIVE';
const REVOKED_STATUS = 'REVOKED';
const VALID_STATUSES = [ACTIVE_STATUS, REVOKED_STATUS];
const ID_REGEX = /^[A-Za-z0-9_-]{3,64}$/;
const ADMIN_MSP_ID = 'Org1MSP';
const ADMIN_OU_PATTERN = /\/OU=admin(?:\/|::)/;

class DeviceRegistry extends Contract {

    // InitLedger — production: idempotent, does NOT seed fake demo keys.
    // Previous demo seeded 0x4F... keys; production requires P-256 SPKI PEMs via RegisterDevice.
    // This method now verifies ledger emptiness and emits an init event.
    async InitLedger(ctx) {
        this._requireAdmin(ctx);
        const iterator = await ctx.stub.getStateByRange('', '');
        let hasState = false;
        let res = await iterator.next();
        if (!res.done) hasState = true;
        await iterator.close();
        if (hasState) {
            console.info('InitLedger: ledger already initialized, skipping');
            return JSON.stringify({ message: 'ledger already initialized' });
        }
        console.info('InitLedger: production ledger initialized (no demo devices seeded)');
        ctx.stub.setEvent('InitLedger', Buffer.from(JSON.stringify({ timestamp: this._txTime(ctx), by: this._clientId(ctx) })));
        return JSON.stringify({ message: 'ledger initialized — register devices via RegisterDevice with P-256 SPKI PEM keys' });
    }

    // RegisterDevice enrolls a new device as ACTIVE. Validates ID and PEM.
    async RegisterDevice(ctx, id, publicKey) {
        this._requireAdmin(ctx);
        this._validateId(id);
        this._validatePublicKey(publicKey);
        const exists = await this.DeviceExists(ctx, id);
        if (exists) {
            throw new Error(`Device ${id} already exists`);
        }
        const now = this._txTime(ctx);
        const device = {
            ID: id,
            PublicKey: publicKey,
            Status: ACTIVE_STATUS,
            RegisteredAt: now,
            UpdatedAt: now,
            RegisteredBy: this._clientId(ctx),
        };
        await ctx.stub.putState(id, Buffer.from(stringify(sortKeysRecursive(device))));
        ctx.stub.setEvent('DeviceRegistered', Buffer.from(JSON.stringify({ id, status: ACTIVE_STATUS, by: this._clientId(ctx), timestamp: now })));
        console.info(`Device ${id} registered by ${this._clientId(ctx)}`);
        return JSON.stringify(device);
    }

    // ReadDevice returns the device record stored in the world state.
    async ReadDevice(ctx, id) {
        const deviceJSON = await ctx.stub.getState(id);
        if (!deviceJSON || deviceJSON.length === 0) {
            throw new Error(`Device ${id} does not exist`);
        }
        return deviceJSON.toString();
    }

    // UpdateDevicePublicKey replaces the public key of an existing device (key rotation).
    async UpdateDevicePublicKey(ctx, id, publicKey) {
        this._requireAdmin(ctx);
        this._validatePublicKey(publicKey);
        const device = await this._getDevice(ctx, id);
        const oldKey = device.PublicKey;
        device.PublicKey = publicKey;
        device.UpdatedAt = this._txTime(ctx);
        device.UpdatedBy = this._clientId(ctx);
        await ctx.stub.putState(id, Buffer.from(stringify(sortKeysRecursive(device))));
        ctx.stub.setEvent('DeviceKeyRotated', Buffer.from(JSON.stringify({ id, by: this._clientId(ctx), timestamp: device.UpdatedAt })));
        console.info(`Device ${id} public key rotated (old ${oldKey.substring(0, 20)}... -> new ${publicKey.substring(0, 20)}...)`);
        return JSON.stringify(device);
    }

    // SetDeviceStatus explicitly sets the device status (ACTIVE or REVOKED).
    async SetDeviceStatus(ctx, id, status) {
        this._requireAdmin(ctx);
        if (!VALID_STATUSES.includes(status)) {
            throw new Error(`Invalid status ${status}; expected ${VALID_STATUSES.join(' or ')}`);
        }
        const device = await this._getDevice(ctx, id);
        const prev = device.Status;
        if (prev === status) return JSON.stringify(device);
        device.Status = status;
        device.UpdatedAt = this._txTime(ctx);
        device.UpdatedBy = this._clientId(ctx);
        await ctx.stub.putState(id, Buffer.from(stringify(sortKeysRecursive(device))));
        ctx.stub.setEvent('DeviceStatusChanged', Buffer.from(JSON.stringify({ id, from: prev, to: status, by: this._clientId(ctx), timestamp: device.UpdatedAt })));
        console.info(`Device ${id} status ${prev} -> ${status} by ${this._clientId(ctx)}`);
        return JSON.stringify(device);
    }

    // RevokeDevice marks a device as REVOKED (convenience wrapper).
    async RevokeDevice(ctx, id) {
        return this.SetDeviceStatus(ctx, id, REVOKED_STATUS);
    }

    // ActivateDevice marks a device as ACTIVE (convenience wrapper).
    async ActivateDevice(ctx, id) {
        return this.SetDeviceStatus(ctx, id, ACTIVE_STATUS);
    }

    // ToggleDeviceStatus flips ACTIVE <-> REVOKED (mirrors the gateway toggle endpoint).
    async ToggleDeviceStatus(ctx, id) {
        this._requireAdmin(ctx);
        const device = await this._getDevice(ctx, id);
        const prev = device.Status;
        device.Status = device.Status === ACTIVE_STATUS ? REVOKED_STATUS : ACTIVE_STATUS;
        device.UpdatedAt = this._txTime(ctx);
        device.UpdatedBy = this._clientId(ctx);
        await ctx.stub.putState(id, Buffer.from(stringify(sortKeysRecursive(device))));
        ctx.stub.setEvent('DeviceStatusToggled', Buffer.from(JSON.stringify({ id, from: prev, to: device.Status, by: this._clientId(ctx), timestamp: device.UpdatedAt })));
        console.info(`Device ${id} toggled ${prev} -> ${device.Status}`);
        return JSON.stringify(device);
    }

    // DeleteDevice removes a device record from the world state (admin only in production).
    async DeleteDevice(ctx, id) {
        this._requireAdmin(ctx);
        const exists = await this.DeviceExists(ctx, id);
        if (!exists) {
            throw new Error(`Device ${id} does not exist`);
        }
        await ctx.stub.deleteState(id);
        ctx.stub.setEvent('DeviceDeleted', Buffer.from(JSON.stringify({ id, by: this._clientId(ctx), timestamp: this._txTime(ctx) })));
        console.info(`Device ${id} deleted by ${this._clientId(ctx)}`);
    }

    // DeviceExists returns true when a device with the given ID is in the world state.
    async DeviceExists(ctx, id) {
        const deviceJSON = await ctx.stub.getState(id);
        return deviceJSON && deviceJSON.length > 0;
    }

    // GetAllDevices returns every device stored in the chaincode namespace.
    // In production, the gateway paginates via range queries; this returns all for dashboard.
    async GetAllDevices(ctx) {
        const allResults = [];
        const iterator = await ctx.stub.getStateByRange('', '');
        let result = await iterator.next();
        while (!result.done) {
            const strValue = Buffer.from(result.value.value.toString()).toString('utf8');
            let record;
            try {
                record = JSON.parse(strValue);
            } catch (err) {
                console.log(err);
                record = strValue;
            }
            // Filter to only device records (must have ID and PublicKey)
            if (record && record.ID && record.PublicKey) {
                allResults.push(record);
            }
            result = await iterator.next();
        }
        await iterator.close();
        return JSON.stringify(allResults);
    }

    // GetDeviceHistory returns the history of a device (for audit).
    async GetDeviceHistory(ctx, id) {
        const iterator = await ctx.stub.getHistoryForKey(id);
        const history = [];
        let res = await iterator.next();
        while (!res.done) {
            const entry = res.value;
            history.push({
                txId: entry.txId,
                timestamp: entry.timestamp ? new Date(entry.timestamp.seconds.low * 1000).toISOString() : null,
                isDelete: entry.isDelete,
                value: entry.value.toString('utf8') ? JSON.parse(entry.value.toString('utf8')) : null,
            });
            res = await iterator.next();
        }
        await iterator.close();
        return JSON.stringify(history);
    }

    // _getDevice loads and parses a device or throws if it does not exist.
    async _getDevice(ctx, id) {
        const deviceJSON = await ctx.stub.getState(id);
        if (!deviceJSON || deviceJSON.length === 0) {
            throw new Error(`Device ${id} does not exist`);
        }
        return JSON.parse(deviceJSON.toString());
    }

    _validateId(id) {
        if (!id || typeof id !== 'string' || !ID_REGEX.test(id)) {
            throw new Error(`Invalid device ID "${id}": must match ${ID_REGEX} (3-64 chars, alphanumeric + _ -)`);
        }
    }

    _validatePublicKey(pem) {
        if (typeof pem !== 'string' || pem.length < 80 || pem.length > 10000) {
            throw new Error('A valid P-256 SPKI public key PEM is required');
        }
        try {
            const key = crypto.createPublicKey(pem);
            const curve = key.asymmetricKeyDetails && key.asymmetricKeyDetails.namedCurve;
            const normalized = value => value.trim().replace(/\r\n/g, '\n');
            const canonicalPem = key.export({ type: 'spki', format: 'pem' });
            if (key.type !== 'public' || key.asymmetricKeyType !== 'ec'
                || !['prime256v1', 'secp256r1', 'P-256'].includes(curve)
                || normalized(pem) !== normalized(canonicalPem)) {
                throw new Error('invalid key type');
            }
        } catch {
            throw new Error('A valid P-256 SPKI public key PEM is required');
        }
    }

    _txTime(ctx) {
        const timestamp = ctx.stub.getTxTimestamp();
        const seconds = typeof timestamp.seconds.toNumber === 'function'
            ? timestamp.seconds.toNumber()
            : Number(timestamp.seconds);
        return new Date(seconds * 1000 + Math.floor(timestamp.nanos / 1e6)).toISOString();
    }

    _requireAdmin(ctx) {
        const identity = ctx.clientIdentity;
        const mspId = identity && identity.getMSPID();
        const clientId = identity && identity.getID();
        if (mspId !== ADMIN_MSP_ID || !ADMIN_OU_PATTERN.test(clientId || '')) {
            throw new Error(`Access denied: ${ADMIN_MSP_ID} admin identity required`);
        }
    }

    _clientId(ctx) {
        try {
            const id = ctx.clientIdentity;
            if (!id) return 'unknown';
            return `${id.getMSPID()}:${id.getID()}`.substring(0, 120);
        } catch {
            return 'unknown';
        }
    }
}

module.exports = DeviceRegistry;
